/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package gt.trading.huobi;

import gt.trading.huobi.features.BestBid;
import gt.trading.huobi.features.BestAsk;
import gt.trading.huobi.features.MidPrice;

public class App {
  public static void main(String[] args) {
    // new OrderBook();
    try {
      FeatureGraph fg = new FeatureGraph.Builder().register(new BestBid())
          .register(new BestAsk()).register(new MidPrice()).build();
    } catch (Exception e) {
      System.out.println(e);
    }
  }
}
