/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package gt.trading.huobi;

import gt.trading.huobi.featuregraph.DefaultFeatureGraph;
import gt.trading.huobi.featuregraph.FeatureGraphRunner;

public class App {
  public static void main(String[] args) {
    // new OrderBook();
    try {
      FeatureGraphRunner.run(
          "src/main/java/gt/trading/huobi/featuregraph/config/example.json");

      // FeatureGraphRunner.run("Feature.java");

    } catch (Exception e) {
      System.out.println(e);
    }
  }
}
